// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP_CORE_H_
#define VERILATED_VTOP_CORE_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop_core final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(start,0,0);
        VL_OUT8(done,0,0);
        VL_IN8(block_id,7,0);
        VL_IN8(thread_count,2,0);
        VL_OUT8(program_mem_read_valid,0,0);
        VL_OUT8(program_mem_read_address,7,0);
        VL_IN8(program_mem_read_ready,0,0);
        VL_OUT8(data_mem_read_valid,3,0);
        VL_IN8(data_mem_read_ready,3,0);
        VL_OUT8(data_mem_write_valid,3,0);
        VL_IN8(data_mem_write_ready,3,0);
        CData/*2:0*/ core_state;
        CData/*2:0*/ fetcher_state;
        CData/*7:0*/ current_pc;
        CData/*3:0*/ decoded_rd_address;
        CData/*3:0*/ decoded_rs_address;
        CData/*3:0*/ decoded_rt_address;
        CData/*2:0*/ decoded_nzp;
        CData/*7:0*/ decoded_immediate;
        CData/*0:0*/ decoded_reg_write_enable;
        CData/*0:0*/ decoded_mem_read_enable;
        CData/*0:0*/ decoded_mem_write_enable;
        CData/*0:0*/ decoded_nzp_write_enable;
        CData/*1:0*/ decoded_reg_input_mux;
        CData/*1:0*/ decoded_alu_arithmetic_mux;
        CData/*0:0*/ decoded_alu_output_mux;
        CData/*0:0*/ decoded_pc_mux;
        CData/*0:0*/ decoded_ret;
        CData/*0:0*/ fetcher_instance__DOT__clk;
        CData/*0:0*/ fetcher_instance__DOT__reset;
        CData/*2:0*/ fetcher_instance__DOT__core_state;
        CData/*7:0*/ fetcher_instance__DOT__current_pc;
        CData/*0:0*/ fetcher_instance__DOT__mem_read_valid;
        CData/*7:0*/ fetcher_instance__DOT__mem_read_address;
        CData/*0:0*/ fetcher_instance__DOT__mem_read_ready;
        CData/*2:0*/ fetcher_instance__DOT__fetcher_state;
        CData/*0:0*/ decoder_instance__DOT__clk;
        CData/*0:0*/ decoder_instance__DOT__reset;
        CData/*2:0*/ decoder_instance__DOT__core_state;
        CData/*3:0*/ decoder_instance__DOT__decoded_rd_address;
        CData/*3:0*/ decoder_instance__DOT__decoded_rs_address;
        CData/*3:0*/ decoder_instance__DOT__decoded_rt_address;
        CData/*2:0*/ decoder_instance__DOT__decoded_nzp;
        CData/*7:0*/ decoder_instance__DOT__decoded_immediate;
        CData/*0:0*/ decoder_instance__DOT__decoded_reg_write_enable;
        CData/*0:0*/ decoder_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ decoder_instance__DOT__decoded_mem_write_enable;
        CData/*0:0*/ decoder_instance__DOT__decoded_nzp_write_enable;
        CData/*1:0*/ decoder_instance__DOT__decoded_reg_input_mux;
        CData/*1:0*/ decoder_instance__DOT__decoded_alu_arithmetic_mux;
        CData/*0:0*/ decoder_instance__DOT__decoded_alu_output_mux;
        CData/*0:0*/ decoder_instance__DOT__decoded_pc_mux;
        CData/*0:0*/ decoder_instance__DOT__decoded_ret;
        CData/*0:0*/ scheduler_instance__DOT__clk;
        CData/*0:0*/ scheduler_instance__DOT__reset;
        CData/*0:0*/ scheduler_instance__DOT__start;
        CData/*0:0*/ scheduler_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ scheduler_instance__DOT__decoded_mem_write_enable;
        CData/*0:0*/ scheduler_instance__DOT__decoded_ret;
        CData/*2:0*/ scheduler_instance__DOT__fetcher_state;
        CData/*7:0*/ scheduler_instance__DOT__current_pc;
        CData/*2:0*/ scheduler_instance__DOT__core_state;
    };
    struct {
        CData/*0:0*/ scheduler_instance__DOT__done;
        CData/*0:0*/ scheduler_instance__DOT__unnamedblk1__DOT__any_lsu_waiting;
        CData/*0:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__core_state;
        CData/*1:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux;
        CData/*0:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__decoded_alu_output_mux;
        CData/*7:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__rt;
        CData/*7:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__alu_out;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__core_state;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_valid;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_address;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_ready;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_data;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_valid;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_address;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_data;
        CData/*0:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_ready;
        CData/*1:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__lsu_state;
        CData/*7:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__lsu_out;
        CData/*0:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__enable;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__block_id;
        CData/*2:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__core_state;
        CData/*3:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rd_address;
        CData/*3:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rs_address;
        CData/*3:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rt_address;
        CData/*0:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_reg_write_enable;
        CData/*1:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_reg_input_mux;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__decoded_immediate;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__lsu_out;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__core_state;
        CData/*2:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_nzp;
        CData/*7:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_immediate;
        CData/*0:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable;
        CData/*0:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_pc_mux;
        CData/*7:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__current_pc;
        CData/*7:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__next_pc;
        CData/*2:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__nzp;
        CData/*0:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__core_state;
        CData/*1:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux;
        CData/*0:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__decoded_alu_output_mux;
        CData/*7:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__rt;
    };
    struct {
        CData/*7:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__alu_out;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__core_state;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_valid;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_address;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_ready;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_data;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_valid;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_address;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_data;
        CData/*0:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_ready;
        CData/*1:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__lsu_state;
        CData/*7:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__lsu_out;
        CData/*0:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__enable;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__block_id;
        CData/*2:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__core_state;
        CData/*3:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rd_address;
        CData/*3:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rs_address;
        CData/*3:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rt_address;
        CData/*0:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_reg_write_enable;
        CData/*1:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_reg_input_mux;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__decoded_immediate;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__lsu_out;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__core_state;
        CData/*2:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_nzp;
        CData/*7:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_immediate;
        CData/*0:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable;
        CData/*0:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_pc_mux;
        CData/*7:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__current_pc;
        CData/*7:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__next_pc;
        CData/*2:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__nzp;
        CData/*0:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__core_state;
        CData/*1:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux;
        CData/*0:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__decoded_alu_output_mux;
        CData/*7:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__rt;
        CData/*7:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__alu_out;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__core_state;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_valid;
    };
    struct {
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_address;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_ready;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_data;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_valid;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_address;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_data;
        CData/*0:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_ready;
        CData/*1:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__lsu_state;
        CData/*7:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__lsu_out;
        CData/*0:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__enable;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__block_id;
        CData/*2:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__core_state;
        CData/*3:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rd_address;
        CData/*3:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rs_address;
        CData/*3:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rt_address;
        CData/*0:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_reg_write_enable;
        CData/*1:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_reg_input_mux;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__decoded_immediate;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__lsu_out;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__core_state;
        CData/*2:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_nzp;
        CData/*7:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_immediate;
        CData/*0:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable;
        CData/*0:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_pc_mux;
        CData/*7:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__current_pc;
        CData/*7:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__next_pc;
        CData/*2:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__nzp;
        CData/*0:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__core_state;
        CData/*1:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux;
        CData/*0:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__decoded_alu_output_mux;
        CData/*7:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__rt;
        CData/*7:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__alu_out;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__core_state;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_valid;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_address;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_ready;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_data;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_valid;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_address;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_data;
        CData/*0:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_ready;
        CData/*1:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__lsu_state;
        CData/*7:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__lsu_out;
        CData/*0:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__clk;
    };
    struct {
        CData/*0:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__enable;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__block_id;
        CData/*2:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__core_state;
        CData/*3:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rd_address;
        CData/*3:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rs_address;
        CData/*3:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rt_address;
        CData/*0:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_reg_write_enable;
        CData/*1:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_reg_input_mux;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__decoded_immediate;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__lsu_out;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__rs;
        CData/*7:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__rt;
        CData/*0:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__clk;
        CData/*0:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__reset;
        CData/*0:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__enable;
        CData/*2:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__core_state;
        CData/*2:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_nzp;
        CData/*7:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_immediate;
        CData/*0:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable;
        CData/*0:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_pc_mux;
        CData/*7:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__alu_out;
        CData/*7:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__current_pc;
        CData/*7:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__next_pc;
        CData/*2:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__nzp;
        VL_IN16(program_mem_read_data,15,0);
        SData/*15:0*/ instruction;
        SData/*15:0*/ fetcher_instance__DOT__mem_read_data;
        SData/*15:0*/ fetcher_instance__DOT__instruction;
        SData/*15:0*/ decoder_instance__DOT__instruction;
        SData/*8:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff;
        SData/*8:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff;
        SData/*8:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff;
        SData/*8:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff;
        IData/*31:0*/ scheduler_instance__DOT__unnamedblk1__DOT__unnamedblk2__DOT__i;
        VL_OUT8(data_mem_read_address[4],7,0);
        VL_IN8(data_mem_read_data[4],7,0);
        VL_OUT8(data_mem_write_address[4],7,0);
        VL_OUT8(data_mem_write_data[4],7,0);
        VlUnpacked<CData/*7:0*/, 4> next_pc;
        VlUnpacked<CData/*7:0*/, 4> rs;
        VlUnpacked<CData/*7:0*/, 4> rt;
        VlUnpacked<CData/*1:0*/, 4> lsu_state;
        VlUnpacked<CData/*7:0*/, 4> lsu_out;
        VlUnpacked<CData/*7:0*/, 4> alu_out;
        VlUnpacked<CData/*1:0*/, 4> scheduler_instance__DOT__lsu_state;
        VlUnpacked<CData/*7:0*/, 4> scheduler_instance__DOT__next_pc;
        VlUnpacked<CData/*7:0*/, 16> threads__BRA__0__KET____DOT__register_instance__DOT__registers;
        VlUnpacked<CData/*7:0*/, 16> threads__BRA__1__KET____DOT__register_instance__DOT__registers;
        VlUnpacked<CData/*7:0*/, 16> threads__BRA__2__KET____DOT__register_instance__DOT__registers;
        VlUnpacked<CData/*7:0*/, 16> threads__BRA__3__KET____DOT__register_instance__DOT__registers;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ fetcher_instance__DOT__IDLE = 0U;
    static constexpr CData/*2:0*/ fetcher_instance__DOT__FETCHING = 1U;
    static constexpr CData/*2:0*/ fetcher_instance__DOT__FETCHED = 2U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__NOP = 0U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__BRnzp = 1U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__CMP = 2U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__ADD = 3U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__SUB = 4U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__MUL = 5U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__DIV = 6U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__LDR = 7U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__STR = 8U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__CONST = 9U;
    static constexpr CData/*3:0*/ decoder_instance__DOT__RET = 0x0fU;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__IDLE = 0U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__FETCH = 1U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__DECODE = 2U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__REQUEST = 3U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__WAIT = 4U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__EXECUTE = 5U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__UPDATE = 6U;
    static constexpr CData/*2:0*/ scheduler_instance__DOT__DONE_S = 7U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__ADD = 0U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__SUB = 1U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__MUL = 2U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__alu_instance__DOT__DIV = 3U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__REQUESTING = 1U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__WAITING = 2U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__lsu_instance__DOT__DONE = 3U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__ARITHMETIC = 0U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__MEMORY = 1U;
    static constexpr CData/*1:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__CONSTANT = 2U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__ADD = 0U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__SUB = 1U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__MUL = 2U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__alu_instance__DOT__DIV = 3U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__REQUESTING = 1U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__WAITING = 2U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__lsu_instance__DOT__DONE = 3U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__ARITHMETIC = 0U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__MEMORY = 1U;
    static constexpr CData/*1:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__CONSTANT = 2U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__ADD = 0U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__SUB = 1U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__MUL = 2U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__alu_instance__DOT__DIV = 3U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__REQUESTING = 1U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__WAITING = 2U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__lsu_instance__DOT__DONE = 3U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__ARITHMETIC = 0U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__MEMORY = 1U;
    static constexpr CData/*1:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__CONSTANT = 2U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__ADD = 0U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__SUB = 1U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__MUL = 2U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__alu_instance__DOT__DIV = 3U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__REQUESTING = 1U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__WAITING = 2U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__lsu_instance__DOT__DONE = 3U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__ARITHMETIC = 0U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__MEMORY = 1U;
    static constexpr CData/*1:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__CONSTANT = 2U;
    static constexpr IData/*31:0*/ DATA_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ PROGRAM_MEM_DATA_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ fetcher_instance__DOT__PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ fetcher_instance__DOT__PROGRAM_MEM_DATA_BITS = 0x00000010U;
    static constexpr IData/*31:0*/ scheduler_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__THREAD_ID = 0U;
    static constexpr IData/*31:0*/ threads__BRA__0__KET____DOT__register_instance__DOT__DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__0__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__THREAD_ID = 1U;
    static constexpr IData/*31:0*/ threads__BRA__1__KET____DOT__register_instance__DOT__DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__1__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__THREAD_ID = 2U;
    static constexpr IData/*31:0*/ threads__BRA__2__KET____DOT__register_instance__DOT__DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__2__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__THREADS_PER_BLOCK = 4U;
    static constexpr IData/*31:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__THREAD_ID = 3U;
    static constexpr IData/*31:0*/ threads__BRA__3__KET____DOT__register_instance__DOT__DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__DATA_MEM_DATA_BITS = 8U;
    static constexpr IData/*31:0*/ threads__BRA__3__KET____DOT__pc_instance__DOT__PROGRAM_MEM_ADDR_BITS = 8U;

    // CONSTRUCTORS
    Vtop_core(Vtop__Syms* symsp, const char* v__name);
    ~Vtop_core();
    VL_UNCOPYABLE(Vtop_core);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
