// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtop.h for the primary calling header

#include "Vtop__pch.h"
#include "Vtop_core.h"

VL_ATTR_COLD void Vtop_core___ctor_var_reset(Vtop_core* vlSelf) {
    VL_DEBUG_IF(VL_DBG_MSGF("+          Vtop_core___ctor_var_reset\n"); );
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    vlSelf->clk = 0;
    vlSelf->reset = 0;
    vlSelf->start = 0;
    vlSelf->done = 0;
    vlSelf->block_id = 0;
    vlSelf->thread_count = 0;
    vlSelf->program_mem_read_valid = 0;
    vlSelf->program_mem_read_address = 0;
    vlSelf->program_mem_read_ready = 0;
    vlSelf->program_mem_read_data = 0;
    vlSelf->data_mem_read_valid = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->data_mem_read_address[__Vi0] = 0;
    }
    vlSelf->data_mem_read_ready = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->data_mem_read_data[__Vi0] = 0;
    }
    vlSelf->data_mem_write_valid = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->data_mem_write_address[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->data_mem_write_data[__Vi0] = 0;
    }
    vlSelf->data_mem_write_ready = 0;
    vlSelf->core_state = 0;
    vlSelf->fetcher_state = 0;
    vlSelf->instruction = 0;
    vlSelf->current_pc = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->next_pc[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->rs[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->rt[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->lsu_state[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->lsu_out[__Vi0] = 0;
    }
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->alu_out[__Vi0] = 0;
    }
    vlSelf->decoded_rd_address = 0;
    vlSelf->decoded_rs_address = 0;
    vlSelf->decoded_rt_address = 0;
    vlSelf->decoded_nzp = 0;
    vlSelf->decoded_immediate = 0;
    vlSelf->decoded_reg_write_enable = 0;
    vlSelf->decoded_mem_read_enable = 0;
    vlSelf->decoded_mem_write_enable = 0;
    vlSelf->decoded_nzp_write_enable = 0;
    vlSelf->decoded_reg_input_mux = 0;
    vlSelf->decoded_alu_arithmetic_mux = 0;
    vlSelf->decoded_alu_output_mux = 0;
    vlSelf->decoded_pc_mux = 0;
    vlSelf->decoded_ret = 0;
    vlSelf->fetcher_instance__DOT__clk = 0;
    vlSelf->fetcher_instance__DOT__reset = 0;
    vlSelf->fetcher_instance__DOT__core_state = 0;
    vlSelf->fetcher_instance__DOT__current_pc = 0;
    vlSelf->fetcher_instance__DOT__mem_read_valid = 0;
    vlSelf->fetcher_instance__DOT__mem_read_address = 0;
    vlSelf->fetcher_instance__DOT__mem_read_ready = 0;
    vlSelf->fetcher_instance__DOT__mem_read_data = 0;
    vlSelf->fetcher_instance__DOT__fetcher_state = 0;
    vlSelf->fetcher_instance__DOT__instruction = 0;
    vlSelf->decoder_instance__DOT__clk = 0;
    vlSelf->decoder_instance__DOT__reset = 0;
    vlSelf->decoder_instance__DOT__core_state = 0;
    vlSelf->decoder_instance__DOT__instruction = 0;
    vlSelf->decoder_instance__DOT__decoded_rd_address = 0;
    vlSelf->decoder_instance__DOT__decoded_rs_address = 0;
    vlSelf->decoder_instance__DOT__decoded_rt_address = 0;
    vlSelf->decoder_instance__DOT__decoded_nzp = 0;
    vlSelf->decoder_instance__DOT__decoded_immediate = 0;
    vlSelf->decoder_instance__DOT__decoded_reg_write_enable = 0;
    vlSelf->decoder_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->decoder_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->decoder_instance__DOT__decoded_nzp_write_enable = 0;
    vlSelf->decoder_instance__DOT__decoded_reg_input_mux = 0;
    vlSelf->decoder_instance__DOT__decoded_alu_arithmetic_mux = 0;
    vlSelf->decoder_instance__DOT__decoded_alu_output_mux = 0;
    vlSelf->decoder_instance__DOT__decoded_pc_mux = 0;
    vlSelf->decoder_instance__DOT__decoded_ret = 0;
    vlSelf->scheduler_instance__DOT__clk = 0;
    vlSelf->scheduler_instance__DOT__reset = 0;
    vlSelf->scheduler_instance__DOT__start = 0;
    vlSelf->scheduler_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->scheduler_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->scheduler_instance__DOT__decoded_ret = 0;
    vlSelf->scheduler_instance__DOT__fetcher_state = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->scheduler_instance__DOT__lsu_state[__Vi0] = 0;
    }
    vlSelf->scheduler_instance__DOT__current_pc = 0;
    for (int __Vi0 = 0; __Vi0 < 4; ++__Vi0) {
        vlSelf->scheduler_instance__DOT__next_pc[__Vi0] = 0;
    }
    vlSelf->scheduler_instance__DOT__core_state = 0;
    vlSelf->scheduler_instance__DOT__done = 0;
    vlSelf->scheduler_instance__DOT__unnamedblk1__DOT__any_lsu_waiting = 0;
    vlSelf->scheduler_instance__DOT__unnamedblk1__DOT__unnamedblk2__DOT__i = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__decoded_alu_output_mux = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__0__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_valid = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_address = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_ready = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_read_data = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_valid = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_address = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_data = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__mem_write_ready = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__lsu_state = 0;
    vlSelf->threads__BRA__0__KET____DOT__lsu_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__clk = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__reset = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__block_id = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rd_address = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rs_address = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_rt_address = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_reg_write_enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_reg_input_mux = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__rs = 0;
    vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__rt = 0;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->threads__BRA__0__KET____DOT__register_instance__DOT__registers[__Vi0] = 0;
    }
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__clk = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__reset = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_nzp = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__decoded_pc_mux = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__current_pc = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__next_pc = 0;
    vlSelf->threads__BRA__0__KET____DOT__pc_instance__DOT__nzp = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__decoded_alu_output_mux = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__1__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_valid = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_address = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_ready = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_read_data = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_valid = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_address = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_data = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__mem_write_ready = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__lsu_state = 0;
    vlSelf->threads__BRA__1__KET____DOT__lsu_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__clk = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__reset = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__block_id = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rd_address = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rs_address = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_rt_address = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_reg_write_enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_reg_input_mux = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__rs = 0;
    vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__rt = 0;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->threads__BRA__1__KET____DOT__register_instance__DOT__registers[__Vi0] = 0;
    }
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__clk = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__reset = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_nzp = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__decoded_pc_mux = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__current_pc = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__next_pc = 0;
    vlSelf->threads__BRA__1__KET____DOT__pc_instance__DOT__nzp = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__decoded_alu_output_mux = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__2__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_valid = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_address = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_ready = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_read_data = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_valid = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_address = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_data = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__mem_write_ready = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__lsu_state = 0;
    vlSelf->threads__BRA__2__KET____DOT__lsu_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__clk = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__reset = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__block_id = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rd_address = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rs_address = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_rt_address = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_reg_write_enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_reg_input_mux = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__rs = 0;
    vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__rt = 0;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->threads__BRA__2__KET____DOT__register_instance__DOT__registers[__Vi0] = 0;
    }
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__clk = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__reset = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_nzp = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__decoded_pc_mux = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__current_pc = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__next_pc = 0;
    vlSelf->threads__BRA__2__KET____DOT__pc_instance__DOT__nzp = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__decoded_alu_arithmetic_mux = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__decoded_alu_output_mux = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__3__KET____DOT__alu_instance__DOT__unnamedblk1__DOT__diff = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__clk = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__reset = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__decoded_mem_read_enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__decoded_mem_write_enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__rs = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__rt = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_valid = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_address = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_ready = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_read_data = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_valid = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_address = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_data = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__mem_write_ready = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__lsu_state = 0;
    vlSelf->threads__BRA__3__KET____DOT__lsu_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__clk = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__reset = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__block_id = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rd_address = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rs_address = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_rt_address = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_reg_write_enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_reg_input_mux = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__lsu_out = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__rs = 0;
    vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__rt = 0;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        vlSelf->threads__BRA__3__KET____DOT__register_instance__DOT__registers[__Vi0] = 0;
    }
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__clk = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__reset = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__core_state = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_nzp = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_immediate = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_nzp_write_enable = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__decoded_pc_mux = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__alu_out = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__current_pc = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__next_pc = 0;
    vlSelf->threads__BRA__3__KET____DOT__pc_instance__DOT__nzp = 0;
}
